### ISSUE TITLE
cannot download collection through mazer

### ISSUE THREAD

**Issue by chris968** [crivetimihai/ansible_virtualization#2]
mazer freeze without any error during download of the collection, all your other collection working correctly, i've read somewhere that trailing slash on galaxy.yml file can cause problem.
"galaxy.yml" of this collection got one on the "documentation" path, all your other projects didn't.

**Comment by crivetimihai** [comment]
As mazer is now deprecated, does `ansible-galaxy collection install crivetimihai.virtualization` solve the issue?

**Comment by chris968** [comment]
Yes, so unfortunately only with ansible 2.9

**Comment by LaurentMarchelli** [comment]
@chris968 
If you do not need to script the installation for deployment, cloning the repository or symbolic linking the clone into ~/.ansible/collections/ansible_collections/crivetimihai/virtualization works with 2.8.5.
Regards.

**Comment by chris968** [comment]
I will probably use something like this or try to move my code to Ansible 2.9, thank you !
